version: '2'
services:
  spotmate:
    build: .
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=http://backend:80
    links:
      - backend
  backend:
    image: clue/json-server
    volumes:
      - ./mock-backend/:/data/
