version: '2'
services:
  spotmate:
    build: .
    #ports:
    #  - "9090:80"
    environment:
      - BACKEND_URL=http://backend:3000/resources
    #links:
    #  - backend
  backend:
    build: ./mock-backend
  testdevice:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    environment:
      - TZ=Europe/Berlin
      - constraint:node==WX7R:WJ3F:XT6Q:YN52:PQZJ:L7AV:QSCT:I7K2:KV6S:V4JR:7DZK:UIAE
    #links:
    #  - spotmate
