version: '2'
services:
  spotmate:
    build: .
    ports:
      - "9090:80"
    environment:
      - BACKEND_URL=http://backend:80
    links:
      - backend
  backend:
    image: clue/json-server
    volumes:
      - ./mock-backend/:/data/
  testdevice:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    links:
      - spotmate
