version: '2'
services:
  frontend:
    build: .
    ports:
      - "9090:80"
    environment:
      - BACKEND_URL=http://backend:8080/spotmate
  backend:
    image: spotmate
    environment:
      - MYSQL_CONNECTION_URL=jdbc:mysql://172.17.0.1:3306/spotmate
      - MYSQL_USER=spotmate
      - MYSQL_PASSWORD=spotmate
