version: '2'
services:
  spotmate:
    build: .
    ports:
      - "9090:80"
    environment:
      - BACKEND_URL=http://backend:3000
    links:
      - backend
  backend:
    build: ./mock-backend
  testdevice:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    environment:
      - TZ=Europe/Berlin
    links:
      - spotmate
