spotmate:
  build: .
  ports:
    - "8080:80"
  environment:
    - BACKEND_URL=http://192.168.88.8:8080
#  command: /bin/bash -c "envsubst 'BACKEND_URL' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
